name: DevSecOps Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: |
          python -m pip install semgrep
          semgrep scan --config auto app/juice-shop

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: app/juice-shop
          format: table
          severity: CRITICAL,HIGH

      - name: Secret Scan
        run: echo "Gitleaks"

      - name: Build Docker Image
        run: echo "Docker build"

      - name: Container Scan
        run: echo "Trivy image"
